language: d

d:
  # - ldc-1.8.0 # this has to be the first, because apparently we can't generated docs with other compilers
  - ldc
  - dmd
  - gdc

matrix:
  allow_failures:
    - d: gdc

script:
  - dub run --config=mecca-ut

# notifications:
    # email:
        # on_success: change
        # on_failure: change

# after_success: |-
  # [[ $TRAVIS_JOB_NUMBER = *.1 ]] && # only generate docs once per commit
  # [ $TRAVIS_BRANCH = master ] && # don't overwrite the only docs with branches other than master
  # [ $TRAVIS_PULL_REQUEST = false ] && # don't overwrite the only docs with not-yet-merged pull requests
  # dub build --build=ddox &&
  # pip install ghp-import --user && export PATH=$HOME/.local/bin:$PATH &&
  # ghp-import -n docs &&
  # git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
